export const SET_CURRENT_PATH = 'SET_CURRENT_PATH';
export const SET_MOVIE_LIST = 'SET_MOVIE_LIST';
export const SET_CINEMA_COMPLEX_OPTIONS = 'SET_CINEMA_COMPLEX_OPTIONS';
export const SET_CINEMA_OPTIONS = 'SET_CINEMA_OPTIONS';
export const SET_DATE_OPTIONS = 'SET_DATE_OPTIONS';
export const SET_TIME_OPTIONS = 'SET_TIME_OPTIONS';
export const SET_CINEMA_COMPLEX_INFO = 'SET_CINEMA_COMPLEX_INFO';
export const SET_CINEMA_INFO = 'SET_CINEMA_INFO';
